config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
# app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    run BlogPost::Operation::Index do |ctx|
      @model = ctx[:model]
      @total = @model.count
  
      render
    end
  end

  def new
    run BlogPost::Operation::Create::Present do |ctx|

    @form = ctx["contract.default"]
    render
    end
  end

  def create
    _ctx = run BlogPost::Operation::Create do |ctx|
      return redirect_to blog_posts_path
    end
  
    @form = _ctx["contract.default"]
    render :new
  end

  def edit
    run BlogPost::Operation::Update::Present do |ctx|
      @form   = ctx["contract.default"]
      @title  = "Editing #{ctx[:model].title}"
  
      render
    end
  end

  def update
    _ctx = run BlogPost::Operation::Update do |ctx|
      flash[:notice] = "#{ctx[:model].title} has been saved"
      return redirect_to blog_post_path(ctx[:model].id)
    end
    @form   = _ctx["contract.default"] # FIXME: redundant to #create!
    @title  = "Editing #{_ctx[:model].title}"

    render :edit
  end

  def show
    run BlogPost::Operation::Show do |ctx|
      @model = ctx[:model]
      render
    end
  end

  def destroy
    run BlogPost::Operation::Delete

    flash[:notice] = "Post deleted"
    redirect_to blog_posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.html.erb
# app/views/blog_posts/edit.html.erb
<h1>Editing "<%= @model.title %>"</h1>

<%= simple_form_for @form, as: :blog_post, url: blog_post_path(@model.id), method: :patch do |f| %>
  <div class="row">
      <%= f.input :title, placeholder: "Title", label: false %>
  </div>
  <div class="row">
      <%= f.input :body, placeholder: "Say it out loud!", label: false %>
  </div>
  <div class="row">
      <%= f.submit "Create Post" %>
  </div>
<% end %>

app/views/blog_posts/index.html.erb
# app/views/blog_posts/index.html.erb
<div class="header">
  Total: <%= @total %>
</div>

<%= @model.each do |blog_post| %>
  <h2>
    <%= blog_post.title %>
  </h2>

  <div class="created_at">
    Posted at <%= blog_post.created_at %>
  </div>

  <div class="body">
    <%= blog_post.body %>
  </div>
  <p>
   <%= link_to "Edit", edit_blog_post_path(blog_post.id) %>
  </p>
  <p>
   <%= button_to "Delete", blog_post_path(blog_post.id), method: :delete %>
  </p>

  <hr>
<% end %>

app/views/blog_posts/new.html.erb
<!-- app/views/blog_posts/new.html.erb -->
<h1>New Post</h1>

<%= simple_form_for @form, as: :blog_post, url: blog_posts_path do |f| %>
  <div class="row">
      <%= f.input :title, placeholder: "Title", label: false %>
  </div>
  <div class="row">
      <%= f.input :body, placeholder: "Say it out loud!", label: false %>
  </div>
  <div class="row">
      <%= f.submit "Create Post" %>
  </div>
<% end %>

app/views/blog_posts/show.html.erb
<h2>
  <%= @model.title %>
</h2>

<h2>
  <%= @model.body %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrailblazerDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>